services:
  gates-mcp-blue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gates-mcp-blue
    image: iccm/gates:blue
    ports:
      - "9051:8050"
    environment:
      - GATES_PORT=8050
      - GATES_HOST=0.0.0.0
      - PLAYFAIR_URL=ws://playfair-mcp:8040
      - LOG_LEVEL=info
      - NODE_ENV=production
    volumes:
      - gates-output:/app/output
    networks:
      - iccm_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '2'
        reservations:
          memory: 512M
          cpus: '1'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:8050/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  gates-output:
    driver: local

networks:
  iccm_network:
    external: true
