apiVersion: apps/v1
kind: Deployment
metadata:
  name: sessionmanager
  namespace: sessionmanager-green
  labels:
    app: sessionmanager
    version: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sessionmanager
      version: green
  template:
    metadata:
      labels:
        app: sessionmanager
        version: green
    spec:
      containers:
      - name: sessionmanager
        image: sessionmanager:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: REDIS_URL
          value: "redis://redis-service.sessionmanager.svc.cluster.local:6379"
        - name: MONGODB_URL
          value: "mongodb://mongodb-service.sessionmanager.svc.cluster.local:27017"
        - name: S3_BUCKET_NAME
          value: "session-archive"
        - name: S3_REGION
          value: "us-east-1"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: sessionmanager-secrets
              key: jwt-secret
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: sessionmanager-secrets
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: sessionmanager-secrets
              key: aws-secret-access-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: sessionmanager-green
  namespace: sessionmanager-green
spec:
  selector:
    app: sessionmanager
    version: green
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP