# Create this file as secrets.yaml with actual values before deploying
# kubectl apply -f secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: sessionmanager-secrets
  namespace: sessionmanager
type: Opaque
stringData:
  jwt-secret: "CHANGE_ME_TO_SECURE_SECRET"
  mongo-password: "CHANGE_ME_TO_SECURE_PASSWORD"
  aws-access-key-id: "YOUR_AWS_ACCESS_KEY"
  aws-secret-access-key: "YOUR_AWS_SECRET_KEY"
---
# Apply the same secret to blue and green namespaces
apiVersion: v1
kind: Secret
metadata:
  name: sessionmanager-secrets
  namespace: sessionmanager-blue
type: Opaque
stringData:
  jwt-secret: "CHANGE_ME_TO_SECURE_SECRET"
  mongo-password: "CHANGE_ME_TO_SECURE_PASSWORD"
  aws-access-key-id: "YOUR_AWS_ACCESS_KEY"
  aws-secret-access-key: "YOUR_AWS_SECRET_KEY"
---
apiVersion: v1
kind: Secret
metadata:
  name: sessionmanager-secrets
  namespace: sessionmanager-green
type: Opaque
stringData:
  jwt-secret: "CHANGE_ME_TO_SECURE_SECRET"
  mongo-password: "CHANGE_ME_TO_SECURE_PASSWORD"
  aws-access-key-id: "YOUR_AWS_ACCESS_KEY"
  aws-secret-access-key: "YOUR_AWS_SECRET_KEY"