# docker-compose.yml

version: '3.8'

volumes:
  # PRODUCTION: Using ZFS datasets on physical server (192.168.1.210)
  # ZFS pool: irina (100GB file-based pool on /mnt/storage RAID)
  # Datasets: irina/horace/files and irina/horace/metadata
  irina_storage_files:
    driver: local
    driver_opts:
      type: none
      device: /mnt/irina_storage/files
      o: bind

  irina_storage_metadata:
    driver: local
    driver_opts:
      type: none
      device: /mnt/irina_storage/metadata
      o: bind

services:
  horace-mcp:
    build:
      context: ../..
      dockerfile: mads/horace/Dockerfile
    restart: unless-stopped
    # Run as a non-root user. This UID/GID must match the ownership
    # of the ZFS datasets on the host.
    user: "1000:1000"
    ports:
      - "8000:8000"   # HTTP REST API
      - "9070:9070"   # MCP WebSocket server
    volumes:
      # Mounts the shared files directory (read-write)
      - irina_storage_files:/mnt/irina_storage/files
      # Mounts the private metadata directory
      - irina_storage_metadata:/mnt/irina_storage/.horace
      # Mount /etc/localtime to ensure container time matches host time for snapshots
      - /etc/localtime:/etc/localtime:ro
    environment:
      # Godot Logging Integration
      - GODOT_URL=ws://godot-mcp:9060
      - LOGGING_ENABLED=true

      # These paths match the mount points inside the container
      - HORACE_FILES_PATH=/mnt/irina_storage/files
      - HORACE_METADATA_PATH=/mnt/irina_storage/.horace
      # ZFS snapshots enabled (ZFS pool 'irina' available)
      - ENABLE_ZFS_SNAPSHOTS=true
      - ZFS_DATASET=irina/horace/files
      - LOG_LEVEL=INFO
      # PostgreSQL connection (using shared ICCM PostgreSQL server)
      - DATABASE_URL=postgresql://${HORACE_DB_USER:-horace}:${HORACE_DB_PASSWORD}@${HORACE_DB_HOST:-irina}:${HORACE_DB_PORT:-5432}/${HORACE_DB_NAME:-horace}

    # Networks
    networks:
      - iccm_network

networks:
  iccm_network:
    external: true
