# docker-compose.yml
version: '3.8'

services:
  horace-mcp:
    build: .
    container_name: horace-mcp
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "9070:8070"
    volumes:
      - /tmp/horace_test_storage:/mnt/irina_storage
      - ../iccm-network:/app/iccm-network:ro
    networks:
      - iccm_network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8070/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

networks:
  iccm_network:
    external: true
