version: '3.8'

services:
  fiedler-blue:
    build:
      context: .
      dockerfile: Dockerfile
    image: fiedler-mcp-blue:latest
    container_name: fiedler-mcp-blue
    restart: unless-stopped
    stdin_open: true  # Keep stdin open for MCP stdio protocol
    tty: true         # Allocate pseudo-TTY

    # Load environment from .env file
    env_file:
      - .env

    # Environment variables for configuration
    environment:
      # Godot Logging Integration
      - GODOT_URL=ws://godot-mcp:9060
      - LOGGING_ENABLED=true

      # Required: Subprocess client paths
      - FIEDLER_GEMINI_CLIENT=/app/clients/gemini_client.py
      - FIEDLER_GEMINI_PYTHON=/usr/local/bin/python
      - FIEDLER_GROK_CLIENT=/app/clients/grok_client.py
      - FIEDLER_GROK_PYTHON=/usr/local/bin/python

      # Security: File access controls
      - FIEDLER_ALLOWED_FILE_ROOTS=/app/allowed_files,/mnt/irina_storage/files/fiedler_output,/mnt/projects
      - FIEDLER_MAX_PACKAGE_BYTES=20971520  # 20MB
      - FIEDLER_MAX_FILE_COUNT=100
      - FIEDLER_MAX_LINES=100000

      # Security: Prompt redaction (default)
      - FIEDLER_SAVE_PROMPT=0

      # Security: Require secure keyring
      - FIEDLER_REQUIRE_SECURE_KEYRING=0  # Set to 1 in production

      # Performance: Parallelism control
      - FIEDLER_MAX_WORKERS=4

      # Output directory (now using Horace NAS Gateway shared storage)
      - FIEDLER_OUTPUT_DIR=/mnt/irina_storage/files/fiedler_output

      # API Keys (mount as secrets in production)
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY:-}
      - XAI_API_KEY=${XAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}

    # Volumes
    volumes:
      # Horace NAS Gateway shared storage (read-write for outputs)
      - /mnt/projects/ICCM/irina_storage_test/files:/mnt/irina_storage/files

      # Allowed files directory (read-only)
      - ./allowed_files:/app/allowed_files:ro

      # Direct access to project files (read-only)
      - /mnt/projects:/mnt/projects:ro

      # Client scripts (read-only)
      - /mnt/projects/hawkmoth-ecosystem/tools/gemini-client/gemini_client.py:/app/clients/gemini_client.py:ro
      - /mnt/projects/ICCM/tools/grok_client.py:/app/clients/grok_client.py:ro

      # State persistence
      - fiedler_state:/root/.fiedler

    # Ports
    ports:
      - "9012:8080"  # MCP WebSocket server on port 9012 (Blue)
      - "9013:8081"  # HTTP streaming proxy on port 9013 (Blue)

    # Networks
    networks:
      - fiedler_network
      - iccm_network  # Shared network for KGB integration

    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  fiedler_state:

networks:
  fiedler_network:
    driver: bridge
  iccm_network:
    external: true
